// Domain-agnostic: the cities that concentrate office/tech hiring in a
// country are largely the same regardless of role (data, dev, security...).
export const CITY_HUB_SUGGESTIONS: Record<string, string[]> = {
  FR: ['Paris', 'Lyon', 'Toulouse', 'Lille', 'Nantes'],
  DE: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt'],
  AT: ['Vienna', 'Graz', 'Linz'],
  BE: ['Brussels', 'Antwerp', 'Ghent'],
  BG: ['Sofia', 'Plovdiv'],
  CY: ['Nicosia', 'Limassol'],
  HR: ['Zagreb', 'Split'],
  DK: ['Copenhagen', 'Aarhus'],
  ES: ['Madrid', 'Barcelona', 'Valencia', 'Bilbao'],
  EE: ['Tallinn', 'Tartu'],
  FI: ['Helsinki', 'Tampere', 'Espoo'],
  GR: ['Athens', 'Thessaloniki'],
  HU: ['Budapest', 'Debrecen'],
  IE: ['Dublin', 'Cork'],
  IS: ['Reykjavik'],
  IT: ['Milan', 'Rome', 'Turin', 'Bologna'],
  LV: ['Riga'],
  LI: ['Vaduz'],
  LT: ['Vilnius', 'Kaunas'],
  LU: ['Luxembourg'],
  MT: ['Valletta'],
  NO: ['Oslo', 'Bergen', 'Trondheim'],
  NL: ['Amsterdam', 'Rotterdam', 'Utrecht', 'Eindhoven'],
  PL: ['Warsaw', 'Krakow', 'Wroclaw', 'Poznan'],
  PT: ['Lisbon', 'Porto'],
  CZ: ['Prague', 'Brno'],
  RO: ['Bucharest', 'Cluj-Napoca'],
  GB: ['London', 'Manchester', 'Edinburgh', 'Bristol'],
  SK: ['Bratislava', 'Kosice'],
  SI: ['Ljubljana'],
  SE: ['Stockholm', 'Gothenburg', 'Malmo'],
  CH: ['Zurich', 'Geneva', 'Basel', 'Zug'],
}
